### PR TITLE
Minimize API and add some documentation

### PR DESCRIPTION
**Pull request by aumetra**

### CODE REVIEW

**Comment by aumetra** [comment]
(pinging @jbg because I saw they're not in the list of the repo watchers :P)

**Comment by jbg** [comment]
Thanks @aumetra, I get emails for every event on the repo, so I guess I am a "watcher", not sure if repo owners appear in watchers or not. This looks good, I will merge and then will make a release tomorrow.

**Review by jbg — APPROVED** [review]

**Comment by kushudai** [comment]
Hi @aumetra Thank you for working on removing the x509-certificates dependency!
I was just wondering if the change to no longer expose `RustlsStream` was intentional.
I have a function that returns a `Connection<Socket, RustlsStream<Socket>>` which I can no longer express 😅

**Comment by jbg** [comment]
Hey @kushudai can you share your code, or something minimized from it that shows the issue you're facing? I suspect you can solve it by making the function generic but if we've made life unreasonably difficult for your use case I'd like to know about it so I can fix it :)

**Comment by kushudai** [comment]
Sure, so I have a function that does this
```rust
async fn connect(addresses: HashSet<Endpoint>, database: &str, config: &Configuration, connected_endpoint: Option<&Endpoint>) -> Result<(Client, Connection<Socket, RustlsStream<Socket>>, Endpoint), Error> {
   let connected_endpoint = get_endpoint_and_set_on_postgres_config(Arc::new(addresses), &mut postgres_config)?;
   let connector = get_postgres_connector(&mut postgres_config, database, config)?;
   let (client, connection) = postgres_config.connect(connector).await?;
    Ok((client, connection, connected_endpoint))
}
```

I use this in 2 places. To connect to my database initially.
But also, to watch the returned connection in a separate task (behind a mutex) to recreate a new connection from the endpoints if it does fail
```rust
tokio::spawn(async move {
        loop {
            let connection = connection_mutex.get_mut();
            // `Connection` implements `Future`, and only resolves when the connection is closed, either because a fatal error has
            // occurred, or because its associated `Client` has dropped and all outstanding work has completed.
            if let Err(e) = connection.await {
                let (new_client, new_connection, new_connected_endpoint) =
                    match connect_single_endpoint(
                        nodes.clone(),
                        &cloned_db,
                        &cloned_config,
                        Some(&connected_endpoint.load_full()),
                    )
                    .await
                    {
                        Ok(c) => c,
                        Err(e) => {
                            slog_error!(cloned_logger, "Failed to create client and connection for {service_name}. Error {e}");
                            continue;
                        }
                    };
                slog_warn!(cloned_logger, "Cockroach connection failed. Error {e}. Replacing with {connected_endpoint:?} with {new_connected_endpoint:?}.");

                cloned_client.store(Arc::new(new_client));
                connected_endpoint.store(Arc::new(new_connected_endpoint));
                connection_mutex = Mutex::new(new_connection);
            }
        }
    });
```

**Comment by aumetra** [comment]
Hi! I have an idea that could potentially solve this. Gonna try it out whether it works and let you know

**Comment by aumetra** [comment]
@kushudai You can still address the stream type, albeit in a more convoluted way.

```rust
type Stream<Socket> = <MakeRustlsConnect as MakeTlsConnect<Socket>>::Stream;
```

Having this just allows us more flexibility making changes to the internal API, and to make the API less confusing. Less types = simpler for most people.

This is just an unfortunate side-effect. Is this workaround acceptable for you?

**Comment by aumetra** [comment]
You just need to add this type alias once globally and reuse it throughout your codebase, it will just work

**Comment by aumetra** [comment]
Speaking of, that is still something we need to fix, making `project_stream` private needs to happen

@jbg are you up to do that?

**Comment by kushudai** [comment]
> ```rust
> <MakeRustlsConnect as MakeTlsConnect<Socket>>::Stream;
> ```

Thank you so much! It works. I really should have figured that out myself 😓

**Pull request merged**
