### PR TITLE
Upgrade rustls to 0.18

### PR DESCRIPTION
**Pull request by djc**
Would appreciate a release once this is merged. Thanks for the nice crate!

### CODE REVIEW

**Comment by djc** [comment]
Gentle ping? I'd also be happy to help out with maintenance if you'd like (I've contributed to rustls itself before, and usually closely track rustls releases) or take over your crate completely if you no longer need this code going forward.

**Comment by djc** [comment]
Ping?

**Comment by jbg** [comment]
Apologies, I had misconfigured Github notifications and did not see this nor your pings! Notifications fixed, and will merge this shortly. Thanks for the PR!

**Comment by jbg** [comment]
0.5.0 released to crates.io.

**Comment by djc** [comment]
Thanks!

**Pull request merged**
